[package]
name = "bweet"
version = "0.1.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
clap = "2.33"
bdk = {  path = "../bdk", features = ["key-value-db", "esplora", "compiler", "keys-bip39"], default-features = false }
serde_json = "1.0"
olivia_core = { path = "../olivia/olivia_core", features = ["std"] }
olivia_secp256k1 = { path = "../olivia/olivia_secp256k1", features = ["libsecp_compat"] }
tokio = { version = "1", features = ["rt", "macros", "time", "rt-multi-thread"] }
sha2 = "0.9"
base2048 = "0.2"
chacha20 = { git = "https://github.com/RustCrypto/stream-ciphers.git", features = ["rng", "cipher"] }
serde = { version = "1.0" }
bincode = "1.3.1"
anyhow = "1"
thiserror = "1.0"
structopt = "0.3"
tiny-bip39 = { version = "^0.8" }
miniscript = { version = "5", features = ["serde"] }
term-table = {  version = "1", default-features = false }
reqwest = { version = "0.11", features = ["blocking"] }

[patch.crates-io]
miniscript = { path = "../rust-miniscript" }


[dev-dependencies]
rand = "0.8"
