[package]
name = "bweet"
version = "0.1.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
clap = "2.33"
bdk = {  path = "../bdk", features = ["cli-utils", "key-value-db", "esplora", "compiler", "keys-bip39", "async-interface"], default-features = false }
serde_json = "1.0"
olivia_core = { path = "../olivia/olivia_core", features = ["std"] }
olivia_secp256k1 = { path = "../olivia/olivia_secp256k1", features = ["libsecp_compat"] }
tokio = { version = "0.2", features = ["rt-core", "macros"] }
sha2 = "0.9"
base2048 = "0.2"
byteorder = "1.3"
chacha20 = { version  = "0.5.0", features = ["rng"] }
serde = { version = "1.0" }
bincode = "1.3.1"
anyhow = "1"
thiserror = "1.0"
tiny-bip39 = { version = "^0.7" }
miniscript = { version = "4", features = ["serde"] }


[dev-dependencies]
rand = "0.7"
