[package]
name = "bweet"
version = "0.1.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
clap = "2.33"
magical = { git = "https://github.com/MagicalBitcoin/magical-bitcoin-wallet", features = ["cli-utils", "esplora"], rev = "5d977bc" }
serde_json = "1.0"
olivia_core = { path = "../olivia/olivia_core", features = ["std"] }
olivia_secp256k1 = { path = "../olivia/olivia_secp256k1" }
tokio = { version = "0.2", features = ["rt-core"] }
sha2 = "0.9"
base2048 = "0.2"
byteorder = "1.3"
ecdsa_fun = { path = "../secp256kfun/ecdsa_fun" }
rand_chacha = "0.2"
secp256kfun = { path = "../secp256kfun/secp256kfun", default-defeatures = false, features = ["serialize_hex"] }
serde = { version = "1.0" }
bincode = "1.3.1"
anyhow = "1"
thiserror = "1.0"

[patch.crates-io]
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin/", rev = "478e091" }
miniscript = { git = "https://github.com/MagicalBitcoin/rust-miniscript", branch = "descriptor-public-key" }
