[package]
name = "gun_wallet"
version = "0.5.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"
license = "0BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
bdk = { git = "https://github.com/llfourn/bdk", rev = "5108b75b44032f0461bf737cdc78b76023d7433e", features = ["key-value-db", "esplora", "compiler", "keys-bip39"], default-features = false  }
#bdk = { path = "../bdk", features = ["key-value-db", "esplora", "compiler", "keys-bip39"], default-features = false }
serde_json = "1.0"
olivia_core = { git = "https://github.com/llfourn/olivia", rev = "025cb6ad31b85d3150571b902e3502a16cab88ad" }
olivia_secp256k1 = { git = "https://github.com/llfourn/olivia", features = ["libsecp_compat"], rev = "025cb6ad31b85d3150571b902e3502a16cab88ad" }
olivia_describe = { git = "https://github.com/llfourn/olivia", rev = "025cb6ad31b85d3150571b902e3502a16cab88ad" }
sha2 = "0.9"
base2048 = "2.0.2"
chacha20 = { version = "0.7", features = ["rng", "cipher"] }
serde = { version = "1" }
bincode = "1.3"
anyhow = "1"
thiserror = "1.0"
structopt = "0.3"
miniscript = { version = "6", features = ["serde"] }
term-table = {  version = "1", default-features = false }
ureq = { version = "2", features = ["json"] }
url = "2"

[features]
nightly = ["olivia_secp256k1/nightly"]


[dev-dependencies]
rand = "0.8"
bdk = { git = "https://github.com/llfourn/bdk", rev = "5108b75b44032f0461bf737cdc78b76023d7433e", features = ["key-value-db", "esplora", "compiler", "keys-bip39", "test-esplora", "test-blockchains"], default-features = false  }
#bdk = { path = "../bdk", features = ["key-value-db", "esplora", "compiler", "keys-bip39", "test-esplora", "test-blockchains"], default-features = false }
