[package]
name = "gun_wallet"
version = "0.1.0"
authors = ["LLFourn <lloyd.fourn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
bdk = { git = "https://github.com/llfourn/bdk", branch = "gun", features = ["key-value-db", "esplora", "compiler", "keys-bip39"], default-features = false  }
# bdk = { path = "../bdk", features = ["key-value-db", "esplora", "compiler", "keys-bip39"], default-features = false }
serde_json = "1.0"
olivia_core = { git = "https://github.com/llfourn/olivia", features = ["std"], rev = "ced4ef56" }
olivia_secp256k1 = { git = "https://github.com/llfourn/olivia" , features = ["libsecp_compat"], rev = "ced4ef56" }
sha2 = "0.9"
base2048 = "0.2"
chacha20 = { version = "0.7", features = ["rng", "cipher"] }
serde = { version = "1" }
bincode = "1.3"
anyhow = "1"
thiserror = "1.0"
structopt = "0.3"
miniscript = { version = "5", features = ["serde"] }
term-table = {  version = "1", default-features = false }
reqwest = { version = "0.11", features = ["blocking"] }

[patch.crates-io]
miniscript = { git = "https://github.com/rust-bitcoin/rust-miniscript", features = ["serde"], rev = "7bbc3e4" }


[dev-dependencies]
rand = "0.8"
