name: Clippy check
on: [ pull_request ]
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          # https://github.com/actions-rs/clippy-check/issues/2#issuecomment-538671632
          args: -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
