name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [
           { rust: "1.58.0", args: "" },
           # { rust: "nightly", args: "--features=nightly" } # disable nightly temporarily
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain.rust }}
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1.2.0
      - run: cargo test ${{ matrix.toolchain.args }} --release --verbose
